name: GCP-VM-CICD

on:
  push: 
    branches: [deploy-kmj, deploy-kec, deploy-npr]
  # 💡 PR을 열었을 때 불필요한 에러(빨간 엑스)가 발생하는 것을 방지하기 위해 PR 트리거는 주석 처리했습니다!
  # pull_request: 
  #   branches: [deploy-kmj, deploy-kec, deploy-npr]

jobs:
  build-deploy:
    runs-on: ubuntu-22.04
    steps:  
      - name: "환경변수 세팅"
        run: |
            if [ "${{ github.ref }}" = "refs/heads/deploy-kmj" ]; then
              echo "GCP_VM_HOST=${{ secrets.GCP_VM_HOST_KMJ }}" >> $GITHUB_ENV
              echo "GCP_VM_USERNAME=${{ secrets.GCP_VM_USERNAME_KMJ }}" >> $GITHUB_ENV
              
              echo "GCP_VM_SSHKEY<<EOF" >> $GITHUB_ENV
              echo "${{ secrets.GCP_VM_SSHKEY_KMJ }}" >> $GITHUB_ENV
              echo "EOF" >> $GITHUB_ENV
              
              echo "DOCKER_USERNAME=${{ secrets.DOCKER_USERNAME_KMJ }}" >> $GITHUB_ENV
              echo "DOCKER_PASSWORD=${{ secrets.DOCKER_PASSWORD_KMJ }}" >> $GITHUB_ENV
              
              echo "APPLICATION_SECRET=${{ secrets.APPLICATION_SECRET_KMJ }}" >> $GITHUB_ENV
              echo "ENV=${{ secrets.ENV_KMJ }}" >> $GITHUB_ENV
              echo "FIREBASE_KEY=${{ secrets.FIREBASE_KEY_KMJ }}" >> $GITHUB_ENV
              
              echo "OPENAI_KEY=${{ secrets.OPENAI_KEY_KMJ }}" >> $GITHUB_ENV
              echo "INSIGHT_PROVIDER=${{ secrets.INSIGHT_PROVIDER }}" >> $GITHUB_ENV

            elif [ "${{ github.ref }}" = "refs/heads/deploy-kec" ]; then
              echo "GCP_VM_HOST=${{ secrets.GCP_VM_HOST_KEC }}" >> $GITHUB_ENV
              echo "GCP_VM_USERNAME=${{ secrets.GCP_VM_USERNAME_KEC }}" >> $GITHUB_ENV
              
              echo "GCP_VM_SSHKEY<<EOF" >> $GITHUB_ENV
              echo "${{ secrets.GCP_VM_SSHKEY_KEC }}" >> $GITHUB_ENV
              echo "EOF" >> $GITHUB_ENV
              
              echo "DOCKER_USERNAME=${{ secrets.DOCKER_USERNAME_KEC }}" >> $GITHUB_ENV
              echo "DOCKER_PASSWORD=${{ secrets.DOCKER_PASSWORD_KEC }}" >> $GITHUB_ENV
              
              echo "APPLICATION_SECRET=${{ secrets.APPLICATION_SECRET_KEC }}" >> $GITHUB_ENV
              echo "ENV=${{ secrets.ENV_KEC }}" >> $GITHUB_ENV
              echo "FIREBASE_KEY=${{ secrets.FIREBASE_KEY_KEC }}" >> $GITHUB_ENV
              
              echo "OPENAI_KEY=${{ secrets.OPENAI_KEY_KEC }}" >> $GITHUB_ENV
              echo "INSIGHT_PROVIDER=${{ secrets.INSIGHT_PROVIDER }}" >> $GITHUB_ENV

            elif [ "${{ github.ref }}" = "refs/heads/deploy-npr" ]; then
              echo "GCP_VM_HOST=${{ secrets.GCP_VM_HOST_NPR }}" >> $GITHUB_ENV
              echo "GCP_VM_USERNAME=${{ secrets.GCP_VM_USERNAME_NPR }}" >> $GITHUB_ENV
              
              echo "GCP_VM_SSHKEY<<EOF" >> $GITHUB_ENV
              echo "${{ secrets.GCP_VM_SSHKEY_NPR }}" >> $GITHUB_ENV
              echo "EOF" >> $GITHUB_ENV
              
              echo "DOCKER_USERNAME=${{ secrets.DOCKER_USERNAME_NPR }}" >> $GITHUB_ENV
              echo "DOCKER_PASSWORD=${{ secrets.DOCKER_PASSWORD_NPR }}" >> $GITHUB_ENV
              
              echo "APPLICATION_SECRET=${{ secrets.APPLICATION_SECRET_NPR }}" >> $GITHUB_ENV
              echo "ENV=${{ secrets.ENV_NPR }}" >> $GITHUB_ENV
              echo "FIREBASE_KEY=${{ secrets.FIREBASE_KEY_NPR }}" >> $GITHUB_ENV
              
              echo "OPENAI_KEY=${{ secrets.OPENAI_KEY_NPR }}" >> $GITHUB_ENV
              echo "INSIGHT_PROVIDER=${{ secrets.INSIGHT_PROVIDER }}" >> $GITHUB_ENV
            fi
            
      - name: Setup SSH Key
        run: |
          mkdir -p ~/.ssh
          echo "${{ env.GCP_VM_SSHKEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          
          # 검증
          ssh-keygen -l -f ~/.ssh/id_rsa || echo "Invalid key format"
          
      - name: Checkout
        uses: actions/checkout@v4
          
      - name: Springboot Build and Docker image build and push
        run: |
          echo ${{env.APPLICATION_SECRET}} | base64 --decode > ./src/main/resources/application-secret.yaml
          echo ${{env.FIREBASE_KEY}} | base64 --decode > ./src/main/resources/firebase-key.json
          
          echo "${{env.DOCKER_PASSWORD}}" | docker login -u ${{env.DOCKER_USERNAME}} --password-stdin
          docker build -t ${{env.DOCKER_USERNAME}}/spring-app:latest .
          docker push ${{env.DOCKER_USERNAME}}/spring-app:latest

      - name: GCP SSH REMOTE 원격접속
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{env.GCP_VM_HOST}}
          username: ${{env.GCP_VM_USERNAME}}
          key: ${{env.GCP_VM_SSHKEY}}
          script: |
            cd /home/${{env.GCP_VM_USERNAME}}
            
            # sudo echo 대신 일반 echo 사용 (권한 에러 방지)
            echo ${{env.ENV}} | base64 --decode > .env
            
            # AI 통신을 위한 환경변수 주입
            echo "OPENAI_KEY=${{env.OPENAI_KEY}}" >> .env
            echo "INSIGHT_PROVIDER=${{env.INSIGHT_PROVIDER}}" >> .env
            
            sudo docker compose -f api-docker-compose.yaml pull
            sudo docker compose -f api-docker-compose.yaml down
            sudo docker compose -f api-docker-compose.yaml up -d
